### ISSUE TITLE
JSON data reports null for key teks_per_shared_diagnosis on today and daily_results (first item) section

### ISSUE THREAD

**Issue by jorgej-ramos** [pvieito/Radar-STATS#2]
Probably due to a division by zero or something similar, the key `teks_per_shared_diagnosis` is `null` in the first moments of the day. This causes data recovery problems in external applications, which can lead to complete disabling of their functionalities.

I suggest reporting `0` instead of `null` for better handling.

**Comment by pvieito** [comment]
@jorgej-ramos Hi Jorge! Technically this is an expected behaviour (ie. sometimes TEKs are uploaded but no shared diagnoses are estimated as the TEKs were not generated yesterday and may be older).

I will take a look to try to change that behaviour later today, meanwhile I can recommend you to try to fetch the backend data with [`RadarSTATSKit`](https://github.com/Radar-STATS/Radar-STATS-Swift) which already handles and supports the nullability of `teks_per_shared_diagnosis ` 😄

**Comment by pvieito** [comment]
This should be fixed by [`ebd95e`](https://github.com/Radar-STATS/Radar-STATS/commit/ebd95e32a3f559fec41c4e56bff9925038b5bf98). Thanks!

**Comment by jorgej-ramos** [comment]
Awesome!
